# Generated by Django 4.1.5 on 2023-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkinfo",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="linkinfo",
            name="sortOrderId",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Sort Order Id"
            ),
        ),
    ]
